package cn.whaley.bi.logsys.log2parquet.moretv2x

import cn.whaley.bi.logsys.log2parquet.moretv2x.LogKey._

/**
 * Created by Will on 2015/9/18.
 */
object LogFields {

    val ACCOUNT_ID_DEFAULT = "0"
    val GROUP_ID_DEFAULT = "0"
    val LOG_VERSION_DEFAULT = "01"
    val BUFFER_TIMES_DEFAULT = "0"
    val ACTION_DEFAULT = ""
    val VIDEO_SID_DEFAULT = ""
    val CONTENT_TYPE_DEFAULT = ""

    val OPERATION_E_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        VIDEO_SID, CONTENT_TYPE, ACTION)

    val OPERATION_ACW_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        VIDEO_SID, CONTENT_TYPE)

    val OPERATION_MM_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME)

    val OPERATION_ST_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        CHANNEL_SID)

    val COLLECT_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        COLLECT_TYPE, COLLECT_CONTENT)

    val DETAIL_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, CONTENT_TYPE, VIDEO_SID)

    val DETAIL_SUBJECT_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, SUBJECT_CODE)

    val PLAYVIEW_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, CONTENT_TYPE, VIDEO_SID, EPISODE_SID, DURATION)

    val PLAYQOS_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, SOURCE, CONTENT_TYPE, VIDEO_SID, EPISODE_SID, BUFFER_TIMES, DURATION)

    val PLAY_BAIDU_CLOUD_FIELDS = Array(DATE, DATETIME, LOG_VERSION, EVENT, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, DURATION)

    val LIVE_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME,
        PATH, LIVE_TYPE, CHANNEL_SID, DURATION)

    val INTERVIEW_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT,
        PATH, DURATION)

    val APPRECOMMEND_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT,
        APP_SID, SUBJECT_CODE)

    val ENTER_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, ACCESS_SOURCE)

    val EXIT_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, ACCESS_SOURCE, DURATION)

    val HOMEACCESS_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT,
        ACCESS_AREA, ACCESS_LOCATION)

    val MTV_ACCOUNT_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, PATH)

    val PAGEVIEW_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, PAGE, PATH)

    val POSITION_ACCESS_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT,
        ACCESS_AREA, ACCESS_LOCATION)

    val APPSUBJECT_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, SUBJECT_CODE)

    val STAR_PAGE_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, STAR, PATH)

    val RETRIEVAL_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, PATH, RETRIEVAL_SORT, RETRIEVAL_AREA,
        RETRIEVAL_YEAR, RETRIEVAL_TAG)
    val SET_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, WALLPAPER)

    val HOME_RECOMMEND_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, HOME_TYPE, HOME_CONTENT, HOME_LOCATION)

    val HOME_VIEW_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, DURATION)

    val DANMU_STATUS_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT)

    val DANMU_SWITCH_FIELDS = Array(DATE, DATETIME, LOG_VERSION, APK_SERIES, APK_VERSION, USER_ID,
        ACCOUNT_ID, GROUP_ID, PROMOTION_CHANNEL, WEATHER_CODE, PRODUCT_MODEL, UPLOAD_TIME, EVENT, PROGRAM_SID, PROGRAM_TYPE)
}
