package cn.whaley.bi.logsys.log2parquet.moretv2x

/**
 * Created by Will on 2015/10/9.
 */
object LogKey {

  val DATE = "date"
  val DATETIME = "datetime"
  val IP = "ip"
  val LOG_TYPE = "logType"
  val LOG_VERSION = "logVersion"
  val EVENT = "event"
  val APK_SERIES = "apkSeries"
  val APK_VERSION = "apkVersion"
  val USER_ID = "userId"
  val ACCOUNT_ID = "accountId"
  val GROUP_ID = "groupId"
  val BUFFER_TIMES = "bufferTimes"
  val DURATION = "duration"
  val LIVE_TYPE = "liveType"
  val CHANNEL_SID = "channelSid"
  val PATH = "path"
  val SUBJECT_CODE = "subjectCode"
  val SOURCE = "source"
  val CONTENT_TYPE = "contentType"
  val VIDEO_SID = "videoSid"
  val EPISODE_SID = "episodeSid"
  val COLLECT_TYPE = "collectType"
  val COLLECT_CONTENT = "collectContent"
  val ACTION = "action"
  val PROMOTION_CHANNEL = "promotionChannel"
  val WEATHER_CODE = "weatherCode"
  val PRODUCT_MODEL = "productModel"
  val UPLOAD_TIME = "uploadTime"
  val RAW_LOG = "rawLog"
  val APP_SID = "appSid"
  val ACCESS_SOURCE = "accessSource"
  val ACCESS_AREA = "accessArea"
  val ACCESS_LOCATION = "accessLocation"
  val PAGE = "page"
  val STAR = "star"
  val RETRIEVAL_SORT = "retrievalSort"
  val RETRIEVAL_AREA = "retrievalArea"
  val RETRIEVAL_YEAR = "retrievalYear"
  val RETRIEVAL_TAG =  "retrievalTag"
  val WALLPAPER = "wallpaper"
  val HOME_TYPE = "homeType"
  val HOME_CONTENT = "homeContent"
  val HOME_LOCATION = "homeLocation"
  val WECHAT_ID = "wechatId"
  val TITLE = "title"
  val LINK_TYPE = "linkType"
  val PROGRAM_SID = "programSid"
  val PROGRAM_TYPE = "programType"
}
